-- AEGIS hosted/chat-only mode: persistent memory + chat history backend.
--
-- Run this once in the Supabase Dashboard's SQL Editor (Project -> SQL Editor -> New query
-- -> paste -> Run). It's idempotent (safe to re-run).
--
-- SECURITY NOTE, read before relying on this: AEGIS has no login/auth UI by design (it's a
-- personal assistant, not a multi-tenant app). There is no real per-request identity for
-- Row Level Security to check, so the policies below are deliberately permissive for the
-- `anon` role and rely entirely on the client-supplied `sync_code` query filter for
-- partitioning. This is NOT real access control -- anyone who has your Supabase URL, your
-- anon (public) key, and a given sync_code can read/write that partition. It's the same
-- trust model as an unlisted document link, not a password. Treat the sync_code as
-- something to keep reasonably private, not as a secret that protects sensitive data.

create table if not exists public.facts (
  id bigint generated by default as identity primary key,
  sync_code text not null,
  category text,
  key text not null,
  value text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (sync_code, category, key)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sync_code text not null,
  role text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_facts_sync_code on public.facts (sync_code);
create index if not exists idx_messages_sync_code_created on public.messages (sync_code, created_at);

alter table public.facts enable row level security;
alter table public.messages enable row level security;

drop policy if exists "anon full access" on public.facts;
create policy "anon full access" on public.facts for all to anon using (true) with check (true);

drop policy if exists "anon full access" on public.messages;
create policy "anon full access" on public.messages for all to anon using (true) with check (true);
