// App links used by the open_app tool and Quick Launch tiles.
export const APP_URLS = {
  youtube: 'https://youtube.com',
  spotify: 'https://open.spotify.com',
  github: 'https://github.com',
  gmail: 'https://mail.google.com',
  google: 'https://google.com',
  chatgpt: 'https://chat.openai.com',
  netflix: 'https://netflix.com',
  twitter: 'https://x.com',
  reddit: 'https://reddit.com',
  notion: 'https://notion.so',
  whatsapp: 'https://web.whatsapp.com',
  figma: 'https://figma.com',
  discord: 'https://discord.com/app',
  slack: 'https://app.slack.com',
  zoom: 'https://zoom.us',
  linkedin: 'https://linkedin.com',
  drive: 'https://drive.google.com',
  docs: 'https://docs.google.com',
  sheets: 'https://sheets.google.com',
  maps: 'https://maps.google.com',
  wikipedia: 'https://wikipedia.org',
};
